AUGMENTATION: False
IMAGE_SIZE: [45, 45, 1] # as per base model
BATCH_SIZE: 128
INCLUDE_TOP: False
EPOCHS: 5
CLASSES: 25
WEIGHTS: null
LEARNING_RATE: 0.001
KEEP_DENSE: True
FREEZE_ALL: False
FREEZE_TILL: 10