AUGMENTATION: False
IMAGE_SIZE: [45, 45, 1] # as per base model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 25
WEIGHTS: null
LEARNING_RATE: 0.001
KEEP_DENSE: TRUE
FREEZE_ALL: TRUE
FREEZE_TILL: null